refactor!: rfc for adf
kyanvasu/rfcs pull request #2
Opened 2021-07-30 16:02 UTC by FredPeal

2021-08-03 19:55 UTC, kaioken requested changes

2021-08-03 19:55 UTC, kaioken commented on 002-template.md
> +<br>Example
@FredPeal if we are adding the email template to the DB , we should have a default email template on the app and with a section where if we get new fields they can be iterated to generated 

for $lead->adfExternalEntities as $entitie
{
<{$entitie}>{$entity.value}</$entity>
}

2021-08-03 19:55 UTC, kaioken commented on 002-template.md
> +    'lead' => $arg[0]->toDocuments(),
@FredPeal we would need a trait for leads or enty entity AllowADF ,

So you can do $leads->toADF();

2021-08-03 19:55 UTC, kaioken commented on 002-template.md
> +<?xml version="1.0" encoding="UTF-8"?>
@FredPeal again the $leads->toADF(); should generate this final xml value

2021-08-09 14:11 UTC, rwhite27 approved these changes

2021-08-09 14:38 UTC, merged